version: '3.9'

networks:
  net1:

services:
  db:
    image: postgres
    ports:
      - "5430:5432"
    env_file:
      - .env
    networks:
      net1:
        aliases:
          - database